name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ] # Se déclenche sur ces branches


jobs:
  build:
    runs-on: ubuntu-latest # Utilise une machine Linux virtuelle

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Récupère ton code source

    - name: Set up JDK 21
      uses: actions/setup-java@v4 # Installe Java sur la machine
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven # Mise en cache des dépendances pour aller plus vite
        cache-dependency-path: 'TourGuide/pom.xml' # Chemin vers le pom.xml pour la mise en cache

    - name: Build et Tests avec Maven
      # On utilise 'package' pour générer le fichier .jar
      run: mvn -B package --file TourGuide/pom.xml

    - name: Téléverser le fichier JAR (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: application-java-21 # Le nom du pack de téléchargement
        # Le chemin vers le JAR généré par Maven (souvent dans le dossier 'target')
        path: TourGuide/target/*.jar
        retention-days: 5 # Durée de conservation (optionnel)